import type { Metadata } from "next";
import "../globals.css";
import LeftSection from "@/components/app/LeftSection";
import RightSection from "@/components/app/RightSection";
import Navbar from "@/components/ui/Navbar";
import MobileNavbar from "@/components/ui/MobileNavbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`antialiased`}>
        <main className="flex flex-col lg:flex-row w-full min-h-screen">
          <LeftSection />
          <section className="flex-1 w-full overflow-y-auto relative border-r-[1px] border-border">
            <div>
              <Navbar />
              <MobileNavbar />
              <div className="lg:mt-[100px]">{children}</div>
            </div>
          </section>
          <RightSection />
        </main>
      </body>
    </html>
  );
}
