import type { Metadata } from "next";
import "../globals.css";
import LeftSection from "@/components/app/LeftSection";
import RightSection from "@/components/app/RightSection";
import Navbar from "@/components/ui/Navbar";
import MobileNavbar from "@/components/ui/MobileNavbar";

import { createServerSupabaseClient } from "@/lib/supabaseServer";
import { redirect } from "next/navigation";
import { AuthProvider } from "@/context/AuthContext";
import { Toaster } from "react-hot-toast";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const supabase = await createServerSupabaseClient();

  const {
    data: { user },
  } = await supabase.auth.getUser();

  if (!user) {
    redirect("/auth/login");
  }

  return (
    <html lang="en" suppressHydrationWarning>
      <body className="antialiased">
        <Toaster position="top-center" reverseOrder={false} />
        <AuthProvider>
          <main className="flex flex-col lg:flex-row w-full min-h-screen">
            <LeftSection />
            <section className="flex-1 w-full overflow-y-auto relative border-r-[1px] border-border">
              <div>
                <Navbar />
                <MobileNavbar />
                <div className="lg:mt-[100px]">{children}</div>
              </div>
            </section>
            <RightSection />
          </main>
        </AuthProvider>
      </body>
    </html>
  );
}
